weights: ./runs/train/yolov7/weights/best.pt
cfg: cfg/training/yolov7.yaml
data: ./data/data.yaml
hyp: ./data/hyp.scratch.p5.yaml
epochs: 2
batch_size: 4
img_size:
- 640
- 640
rect: false
resume: false
nosave: false
notest: true
noautoanchor: true
evolve: false
bucket: ''
cache_images: false
image_weights: false
device: ''
multi_scale: false
single_cls: false
adam: false
sync_bn: false
local_rank: -1
workers: 8
project: runs/train
entity: null
name: yolov7
exist_ok: false
quad: false
linear_lr: false
label_smoothing: 0.0
upload_dataset: false
bbox_interval: -1
save_period: -1
artifact_alias: latest
freeze:
- 2
v5_metric: false
world_size: 1
global_rank: -1
save_dir: runs/train/yolov72
total_batch_size: 4
